version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run: npm install
      - run: docker build -t my-image .
      - store_artifacts:
          path: my-image
  push:
    docker:
      - image: circleci/awscli:latest
    steps:
      - checkout
      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 482279614451.dkr.ecr.us-east-1.amazonaws.com/weather-app
      - run: docker tag my-image:latest 482279614451.dkr.ecr.us-east-1.amazonaws.com/weather-app
      - run: docker push 482279614451.dkr.ecr.us-east-1.amazonaws.com/weather-app

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - push:
          requires:
            - build