version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image to ECR
          command: |
            # Build the Docker image
            docker build -t my-image .

            # Tag the image with the ECR repository URI
            image_uri=$(aws ecr describe-repositories --repository-names my-ecr-repo --query 'repositories[0].repositoryUri' --output text)
            docker tag my-image $image_uri:latest

            # Push the image to ECR
            $(aws ecr get-login --no-include-email)
            docker push $image_uri:latest
      - run:
          name: Deploy image to ECS
          command: |
            # Update the ECS service with the new image
            aws ecs update-service --region us-east-1 \
              --cluster my-ecs-cluster \
              --service my-ecs-service \
              --force-new-deployment \
              --task-definition my-ecs-task-definition \
              --container-name my-container \
              --container-image $image_uri:latest
